services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    AsyncAmazonJp\:
      resource: '../../src/'

    AsyncAmazonJp\UI\Controller\:
      resource: '../../src/*/Order/Controller/'
      tags: [ 'controller.service_arguments' ]